### ISSUE TITLE
File "<stdin>", line 1, in <module> NameError: name 'Custom_Widgets' is not defined

### ISSUE THREAD

**Issue by KlausJackson** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#104]
I have tried 2 ways to execute `Custom_Widgets --create-project`, and I also tried it inside, outside of my only virtual environment:
``` 
(base) E:\Work\Python\projects\SMS>python
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> Custom_Widgets --create-project
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Custom_Widgets' is not defined
```
```
(base) E:\Work\Python\projects\SMS>Custom_Widgets --create-project
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Anaconda\Scripts\Custom_Widgets.exe\__main__.py", line 4, in <module>
  File "C:\Users\klaus\AppData\Roaming\Python\Python311\site-packages\Custom_Widgets\__init__.py", line 12, in <module>
    from Custom_Widgets.Qss.SvgToPngIcons import NewIconsGenerator
  File "C:\Users\klaus\AppData\Roaming\Python\Python311\site-packages\Custom_Widgets\Qss\SvgToPngIcons.py", line 35, in <module>
    from PySide6.QtGui import QColor
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.
```

I used `pip list` to check and Custom_Widgets was not installed on inside, outside virtual environment. But when I check the site-packages and scripts directories manually, it's obviously there. My system environment paths are all included. This only happens to Custom_Widgets library.

Is there a way to fix this problem? I don't know what caused the problem...
Thank you all for spending time to read my issue!

**Comment by KhamisiKibet** [comment]
please follow the instructions. Run the command from a regular
terminal/cmd, not a python terminal

**Comment by KlausJackson** [comment]
I did. It was a regular command prompt, I never use Python terminal.

**Comment by KhamisiKibet** [comment]
That's a python terminal. You typed "python" first, which launches a python
terminal

**Comment by KlausJackson** [comment]
You did it in this video XD https://www.youtube.com/watch?v=X8fY8uFgzb4&list=PLJ8t3BKaQLhMLGdz2EfeYRUHZfr-MbgyC&index=124&ab_channel=SpinnTV
Timestamp: 03:10
I was following what you did XD

**Comment by KlausJackson** [comment]
I understand that in that video was for versions < 0.6.9. But still, I didn't use Python terminal in the second output:
```
(base) E:\Work\Python\projects\SMS>Custom_Widgets --create-project
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Anaconda\Scripts\Custom_Widgets.exe\__main__.py", line 4, in <module>
  File "C:\Users\klaus\AppData\Roaming\Python\Python311\site-packages\Custom_Widgets\__init__.py", line 12, in <module>
    from Custom_Widgets.Qss.SvgToPngIcons import NewIconsGenerator
  File "C:\Users\klaus\AppData\Roaming\Python\Python311\site-packages\Custom_Widgets\Qss\SvgToPngIcons.py", line 35, in <module>
    from PySide6.QtGui import QColor
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.
```
And I used pip list to check and Custom_Widgets was not installed on inside, outside virtual environment. But when I check the site-packages and scripts directories manually, it's obviously there.

**Comment by KhamisiKibet** [comment]
open your terminal, type "Custom_Wudgets", don't type anything else. What
you're reporting is not a custom Widgets error,

**Comment by KlausJackson** [comment]
```
E:\Work\Python>Custom_Widgets
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Anaconda\Scripts\Custom_Widgets.exe\__main__.py", line 4, in <module>
  File "C:\Users\klaus\AppData\Roaming\Python\Python311\site-packages\Custom_Widgets\__init__.py", line 12, in <module>
    from Custom_Widgets.Qss.SvgToPngIcons import NewIconsGenerator
  File "C:\Users\klaus\AppData\Roaming\Python\Python311\site-packages\Custom_Widgets\Qss\SvgToPngIcons.py", line 35, in <module>
    from PySide6.QtGui import QColor
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.
```
So I guess it's an import error, I tried StackOverFlow but uninstall everything related to PyQt6 then reinstall didn't work either. Do you have any suggestions?

**Comment by KhamisiKibet** [comment]
Remove other qt bindings, use only one, if it's Pyside6, reinstall pyside6

**Comment by KlausJackson** [comment]
So I created a new virtual environment, install only PySide6 and Custom-Widgets, add things to the system environment path. Thanks dude. It worked.
