### ISSUE TITLE
Value Error 

### ISSUE THREAD

**Issue by OldResolution** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#105]
C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\.venv\Scripts\python.exe C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\main.py 
Traceback (most recent call last):
  File "C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\main.py", line 57, in <module>
    window = MainWindow()
  File "C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\main.py", line 23, in _init_
    loadJsonStyle(self, self.ui, jsonFiles={"json-files/login_style.json"})
  File "C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\.venv\lib\site-packages\Custom_Widgets\JSonStyles\_init_.py", line 55, in loadJsonStyle
    applyJsonStyle(self, update = update)
  File "C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\.venv\lib\site-packages\Custom_Widgets\JSonStyles\_init_.py", line 1161, in applyJsonStyle
    containerWidget.bgColor = QColor(self.getThemeVariableValue(str(QCustomCheckBox["bgColor"])))
  File "C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\.venv\lib\site-packages\Custom_Widgets\_init_.py", line 209, in getThemeVariableValue
    self.defineThemeVarMapping()
  File "C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\.venv\lib\site-packages\Custom_Widgets\_init_.py", line 213, in defineThemeVarMapping
    CreateColorVariable.CreateVariables(self)
  File "C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\.venv\lib\site-packages\Custom_Widgets\Qss\colorsystem.py", line 259, in CreateVariables
    bg_rgb_1 = hex_to_rgb(theme.BG_1)
  File "C:\Users\Tejas\PycharmProjects\pythonProject1\Python-Mini_Project\.venv\lib\site-packages\Custom_Widgets\Qss\colorsystem.py", line 39, in hex_to_rgb
    r = int(hex_color[0:2], 16)
ValueError: invalid literal for int() with base 16: 'wh'

Process finished with exit code 1
currently doing a project and only one of our devices has this problem while the project is running in all other devices 
Could you please look into this and report what could be the error
Windows 11 Dell G15

**Comment by ArmaganUyanik** [comment]
As far as I understand, this error is caused by the defauly definition of the Light theme, which uses "white" for background color. In my case, it was resolved by adding my own theme settings into the styles.json file as follow:

	"QSettings": [
        {
            "ThemeSettings": [
                {
                    "CustomTheme": [
                        {
                            "Background-color": "#your-background-color-in-hex",
                            "Text-color": "#your-text-color-in-hex",
                            "Accent-color": "#your-accent-color-in-hex",
                            "Theme-name": "your-theme-name",
                            "Default-Theme": true
                        }
                    ]
                }
            ],

**Comment by OldResolution** [comment]
Thanks .That solved the error
