### ISSUE TITLE
I got this error when trying to launch the file

### ISSUE THREAD

**Issue by Sxvxgee** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#11]
```py
Traceback (most recent call last):
  File "C:\Users\aboud\Desktop\New folder\main.py", line 12, in <module>
    from ui_interface import *
  File "C:\Users\aboud\Desktop\New folder\ui_interface.py", line 15, in <module>
    import QSS_Resources_rc
  File "C:\Users\aboud\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'QSS_Resources_rc'
```
how do I fix it?

**Comment by KhamisiKibet** [comment]
Did you use the project maker?

**Comment by Sxvxgee** [comment]
Yeah, I used the project maker and when I inputted 'Y' to launch the main file I got that error. I closed the wizard and tried double clicking main.py but it didnt work and gave me that error

**Comment by KhamisiKibet** [comment]
Sorry about that, let me update it

**Comment by Sxvxgee** [comment]
Okay, thanks! Also please let me know when it's fixed so I reinstall it and use it. Also, I just wanted to note that in `api.py` file, you should change the line
```py
from collections import Mapping, Sequence
```
to
```py
from collections.abc import Mapping, Sequence
```
See: https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections

**Comment by KhamisiKibet** [comment]
If you encounter this error
```python
[WinError 267] The directory name is invalid: 'C:\\Users\\kibet\\Desktop\\testprojectmaker\\QSS\\00bcff'
Traceback (most recent call last):
  File "C:\Users\kibet\anaconda3\lib\site-packages\Custom_Widgets\WidgetsWorker.py", line 82, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\kibet\anaconda3\lib\site-packages\Custom_Widgets\Widgets.py", line 912, in compileSassTheme
    NewIconsGenerator.generateNewIcons(self, progress_callback)
  File "C:\Users\kibet\anaconda3\lib\site-packages\Custom_Widgets\Qss\SvgToPngIcons.py", line 140, in generateNewIcons
    file_names = os.listdir(source_dir)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\kibet\\Desktop\\testprojectmaker\\QSS\\00bcff'
```

Check the QSS folder. This error means windows created a file instead of a folder. Delete the created file, in my case, the file name is "00bcff".

Rerun the app again. 

If youre not sure which file to delete, just delete the all files inside the QSS folder except the py, qrc and scss files.
