### ISSUE TITLE
Error running test file on Manjaro

### ISSUE THREAD

**Issue by olielvewen** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#14]
Hi 
I just discovered your application for making great and modern widgets like  analogwidget. Well done.

Before, I must precised than I'm running on Manjaro with the kernel 5.15 and I got Python 3.10 , Pyqt5/6 installed and all is functionnal.

I've downloaded your library with pip without any  issues. If necessary, I can give you the installation.

I've tried to test in two ways. The first in a terminal (yakuake) and the second time after creating a file in geany and run this python file in the geany terminal. I've got this. I precise than I 've called my file customwidgettest.py

`[olivier@fangorn Developpement]$ python customwidgettest.py 
  File "/home/olivier/Developpement/customwidgettest.py", line 4
    form Custom_Widgets.ProgressIndicator import test
         ^^^^^^^^^^^^^^
SyntaxError: invalid syntax
`

Did you clear my light ? 

Thanks a lot by advance.

**Comment by olielvewen** [comment]
Hoops I 've done an error with from in my import.

I've modified it and run it again in the terminal and I've still an issue.

```
python customwidgettest.py 
Traceback (most recent call last):
  File "/home/olivier/Developpement/customwidgettest.py", line 4, in <module>
    from Custom_Widgets.ProgressIndicator import test
  File "/home/olivier/.local/lib/python3.10/site-packages/Custom_Widgets/ProgressIndicator/test.py", line 16, in <module>
    from Custom_Widgets.ProgressIndicator.ui_interface import *
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/olivier/.local/lib/python3.10/site-packages/Custom_Widgets/ProgressIndicator/ui_interface.py", line 15, in <module>
    from Custom_Widgets.Widgets import FormProgressIndicator
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/olivier/.local/lib/python3.10/site-packages/Custom_Widgets/Widgets.py", line 19, in <module>
    from .Qss import SassCompiler
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/olivier/.local/lib/python3.10/site-packages/Custom_Widgets/Qss/SassCompiler.py", line 13, in <module>
    import qtsass
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/olivier/.local/lib/python3.10/site-packages/qtsass/__init__.py", line 28, in <module>
    from qtsass.api import (
  File "/usr/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/olivier/.local/lib/python3.10/site-packages/qtsass/api.py", line 16, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
[olivier@fangorn Developpement]$ 

```

**Comment by olielvewen** [comment]
Did you have a requirement.txt file ?

**Comment by olielvewen** [comment]
I've installed python-collections-extended and modified my script test.

```
#! /usr/bin/env python
# *-* coding: utf-8 *-*

from collections import Mapping, Sequence

from Custom_Widgets.ProgressIndicator import test

test.main()
```

And I 've still an error which is the following.

```
python customwidgettest.py 
Traceback (most recent call last):
  File "/home/olivier/Developpement/customwidgettest.py", line 4, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by olielvewen** [comment]
Perhaps I should add an pyqt import ? Which one ?
