### ISSUE TITLE
py -3.10 | Mapping in collections

### ISSUE THREAD

**Issue by MPruszewicz** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#17]
On Python 3.10 during:
`from Custom_Widgets.ProgressIndicator import test`
There is an import error from collections
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\___Python\Python310\lib\site-packages\Custom_Widgets\ProgressIndicator\test.py", line 16, in <module>
    from Custom_Widgets.ProgressIndicator.ui_interface import *
  File "C:\___Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\___Python\Python310\lib\site-packages\Custom_Widgets\ProgressIndicator\ui_interface.py", line 15, in <module>
    from Custom_Widgets.Widgets import FormProgressIndicator
  File "C:\___Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\___Python\Python310\lib\site-packages\Custom_Widgets\Widgets.py", line 19, in <module>
    from .Qss import SassCompiler
  File "C:\___Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\___Python\Python310\lib\site-packages\Custom_Widgets\Qss\SassCompiler.py", line 13, in <module>
    import qtsass
  File "C:\___Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\___Python\Python310\lib\site-packages\qtsass\__init__.py", line 28, in <module>
    from qtsass.api import (
  File "C:\___Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\___Python\Python310\lib\site-packages\qtsass\api.py", line 16, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (C:\___Python\Python310\lib\collections\__init__.py)

```

**Comment by KhamisiKibet** [comment]
Solved: https://youtu.be/DMYK-58U0Tk
