### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PanosoikoGr** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#20]
i am getting this error when i run the test code

Traceback (most recent call last):
  File "c:\Users\georg\OneDrive\Υπολογιστής\from Custom_Widgets.ProgressIndicator im.py", line 1, in <module>
    from Custom_Widgets.ProgressIndicator import test
  File "C:\Users\georg\AppData\Local\Programs\Python\Python39\lib\site-packages\Custom_Widgets\ProgressIndicator\test.py", line 23, in <module>        
    from Custom_Widgets.ProgressIndicator.ui_interface import *
  File "C:\Users\georg\AppData\Local\Programs\Python\Python39\lib\site-packages\Custom_Widgets\ProgressIndicator\ui_interface.py", line 10, in <module>
    if 'PySide2' in sys.modules:
NameError: name 'sys' is not defined

**Comment by MazenMarei** [comment]
me too

**Comment by SoulThread2597** [comment]
@MazenMarei question, im having the same issue, what version are you running? like python version? and what system? an example = python  3.10, window 11

**Comment by MazenMarei** [comment]
acutely I got rid of this package and started to use pyside6 it's too easy
and you can make any animation you want easily .
Thanks for your asking by the way i'm using windows 10 and python 3.10.4

**Comment by KhamisiKibet** [comment]
Solved, update the module
