### ISSUE TITLE
Problem with PyQt5 Widget

### ISSUE THREAD

**Issue by TSGU5698** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#30]
I make a simple window with PyQt5 code,it works fine when I test it.
But when I import Custom_Widgets.Widgets package ,there are some error with my code.
```python
from PyQt5.Qt import *
import sys
import os
from Custom_Widgets.Widgets import *
from test2 import *


class MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        # loadJsonStyle(self, self.ui)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
```

test2 is my pyqt5 code by qtdesigner
And error message is 
```
Traceback (most recent call last):
  File "D:/Code/test/mian2.py", line 23, in <module>
    window = MainWindow()
  File "D:/Code/test/mian2.py", line 18, in __init__
    self.ui.setupUi(self)
  File "D:\Code\test\test2.py", line 18, in setupUi
    self.centralwidget = QtWidgets.QWidget(MainWindow)
TypeError: QWidget(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'MainWindow'
```

**Comment by muchangdian** [comment]
> 



> 我用 PyQt5 代码制作了一个简单的窗口，当我测试它时它工作正常。 但是当我导入 Custom_Widgets.Widgets 包时，我的代码出现了一些错误。
> 
> ```python
> from PyQt5.Qt import *
> import sys
> import os
> from Custom_Widgets.Widgets import *
> from test2 import *
> 
> 
> class MainWindow(QMainWindow):
>     def __init__(self):
>         QMainWindow.__init__(self)
>         self.ui = Ui_MainWindow()
>         self.ui.setupUi(self)
>         # loadJsonStyle(self, self.ui)
> 
> if __name__ == '__main__':
>     app = QApplication(sys.argv)
>     window = MainWindow()
>     window.show()
>     sys.exit(app.exec_())
> ```
> 
> test2 是 qtdesigner 我的 pyqt5 代码， 错误消息是
> 
> ```
> Traceback (most recent call last):
>   File "D:/Code/test/mian2.py", line 23, in <module>
>     window = MainWindow()
>   File "D:/Code/test/mian2.py", line 18, in __init__
>     self.ui.setupUi(self)
>   File "D:\Code\test\test2.py", line 18, in setupUi
>     self.centralwidget = QtWidgets.QWidget(MainWindow)
> TypeError: QWidget(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'MainWindow'
> ```

This package is made of pyside2 and pyside6,maybe you can try importing it.

**Comment by TSGU5698** [comment]
> > 
> 
> > 我用 PyQt5 代码制作了一个简单的窗口，当我测试它时它工作正常。 但是当我导入 Custom_Widgets.Widgets 包时，我的代码出现了一些错误。
> > ```python
> > from PyQt5.Qt import *
> > import sys
> > import os
> > from Custom_Widgets.Widgets import *
> > from test2 import *
> > 
> > 
> > class MainWindow(QMainWindow):
> >     def __init__(self):
> >         QMainWindow.__init__(self)
> >         self.ui = Ui_MainWindow()
> >         self.ui.setupUi(self)
> >         # loadJsonStyle(self, self.ui)
> > 
> > if __name__ == '__main__':
> >     app = QApplication(sys.argv)
> >     window = MainWindow()
> >     window.show()
> >     sys.exit(app.exec_())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > test2 是 qtdesigner 我的 pyqt5 代码， 错误消息是
> > ```
> > Traceback (most recent call last):
> >   File "D:/Code/test/mian2.py", line 23, in <module>
> >     window = MainWindow()
> >   File "D:/Code/test/mian2.py", line 18, in __init__
> >     self.ui.setupUi(self)
> >   File "D:\Code\test\test2.py", line 18, in setupUi
> >     self.centralwidget = QtWidgets.QWidget(MainWindow)
> > TypeError: QWidget(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'MainWindow'
> > ```
> 
> This package is made of pyside2 and pyside6,maybe you can try importing it.

Thanks for your reply. I imported pyside2 and it works. This package just works in pyside2 and pyside6. PyQt maybe not compatible yet.
