### ISSUE TITLE
I got this by mistake after adding loadJsonStyle to main.py and I couldn't solve it even though I tried for hours

### ISSUE THREAD

**Issue by emircbn16** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#43]
Traceback (most recent call last):
  File "c:\Users\Emir\Desktop\OOPP2\main.py", line 3, in <module>
    from interface import *
  File "c:\Users\Emir\Desktop\OOPP2\interface.py", line 563, in <module>
    from Custom_Widgets.Widgets import QCustomSlideMenu, QCustomStackedWidget
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\Custom_Widgets\Widgets.py", line 20, in <module>
    from .Qss import SassCompiler
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\Custom_Widgets\Qss\SassCompiler.py", line 25, in <module>
    from .SvgToPngIcons import NewIconsGenerator
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\Custom_Widgets\Qss\SvgToPngIcons.py", line 1, in <module>
    import cairosvg
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\Emir\AppData\Roaming\Python\Python310\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by filipellopes** [comment]
i'm also having this issue

**Comment by Jaidoo123** [comment]
I'm also having the same issue.
Here is what I got:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\ProgressIndicator\test.py", line 32, in <module>
    from Custom_Widgets.ProgressIndicator.ui_interface import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\ProgressIndicator\ui_interface.py", line 15, in <module>
    from Custom_Widgets.Widgets import FormProgressIndicator
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Widgets.py", line 19, in <module>
    from .Qss import SassCompiler
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Qss\SassCompiler.py", line 39, in <module>
    from . SvgToPngIcons import NewIconsGenerator
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Qss\SvgToPngIcons.py", line 1, in <module>
    import cairosvg
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by YZDYSJYC** [comment]
我也有这个问题

**Comment by KhamisiKibet** [comment]
Solved https://youtu.be/p2Lws5CyioQ
