### ISSUE TITLE
cairo-2 not found

### ISSUE THREAD

**Issue by AganeNoRenkinjutsushi** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#44]
Hello, 
I have issue installing Custom Widget. I have already install pycairo. I report here the error:
Thanks in advance

>>> from Custom_Widgets.ProgressIndicator import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python_3.9.7\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Python\Python_3.9.7\lib\site-packages\Custom_Widgets\ProgressIndicator\test.py", line 32, in <module>
    from Custom_Widgets.ProgressIndicator.ui_interface import *
  File "C:\Python\Python_3.9.7\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Python\Python_3.9.7\lib\site-packages\Custom_Widgets\ProgressIndicator\ui_interface.py", line 15, in <module>
    from Custom_Widgets.Widgets import FormProgressIndicator
  File "C:\Python\Python_3.9.7\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Python\Python_3.9.7\lib\site-packages\Custom_Widgets\Widgets.py", line 19, in <module>
    from .Qss import SassCompiler
  File "C:\Python\Python_3.9.7\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Python\Python_3.9.7\lib\site-packages\Custom_Widgets\Qss\SassCompiler.py", line 39, in <module>
    from . SvgToPngIcons import NewIconsGenerator
  File "C:\Python\Python_3.9.7\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Python\Python_3.9.7\lib\site-packages\Custom_Widgets\Qss\SvgToPngIcons.py", line 1, in <module>
    import cairosvg
  File "C:\Python\Python_3.9.7\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Python\Python_3.9.7\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Python\Python_3.9.7\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Python\Python_3.9.7\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Python\Python_3.9.7\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Python\Python_3.9.7\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Python\Python_3.9.7\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by AganeNoRenkinjutsushi** [comment]
Found the solution in your youtube community section:
For Windows users:
if you're getting Cairo SVG error when using the custom widgets module, solve it here:
[https://github.com/KhamisiKibet/QT-Py...](https://www.youtube.com/redirect?event=backstage_event&redir_token=QUFFLUhqbDJQNTI5WnhGT3ptOW92UVZhdG12NTY4a29iUXxBQ3Jtc0trUkdSUGNFcUJvdURJVldqUjVHcURmbVhQdEhYZEZOOV9YRWs4Q2VERWxQRTZDOWdaaU9ZSG5DeERjWnhZMFF2eHBPMnVQalZfSmlaSU5YSms2UDJmT1lzcGFrbzNHVF9PRHMyUGdyUHFWUjJXUVI1VQ&q=https%3A%2F%2Fgithub.com%2FKhamisiKibet%2FQT-PyQt-PySide-Custom-Widgets%2Fissues%2F8%23issuecomment-1059071881)

**Comment by AganeNoRenkinjutsushi** [comment]
Found the solution in your YouTube Community section:

For Windows users:
if you're getting Cairo SVG error when using the custom widgets module, solve it here:
[https://github.com/KhamisiKibet/QT-Py...](https://www.youtube.com/redirect?event=backstage_event&redir_token=QUFFLUhqbDJQNTI5WnhGT3ptOW92UVZhdG12NTY4a29iUXxBQ3Jtc0trUkdSUGNFcUJvdURJVldqUjVHcURmbVhQdEhYZEZOOV9YRWs4Q2VERWxQRTZDOWdaaU9ZSG5DeERjWnhZMFF2eHBPMnVQalZfSmlaSU5YSms2UDJmT1lzcGFrbzNHVF9PRHMyUGdyUHFWUjJXUVI1VQ&q=https%3A%2F%2Fgithub.com%2FKhamisiKibet%2FQT-PyQt-PySide-Custom-Widgets%2Fissues%2F8%23issuecomment-1059071881)

**Comment by matheo-gif** [comment]
i cant find solution in youtube...
