### ISSUE TITLE
QRect- overloaded error

### ISSUE THREAD

**Issue by islamshahine** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#48]
I have that error after applying Notification button and apply the JS code, after running:
this error appears:
" Traceback (most recent call last):
  File "C:\Users\IslamShahin\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Widgets.py", line 1466, in paintEvent
    self.floatMenu()
  File "C:\Users\IslamShahin\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Widgets.py", line 1152, in floatMenu
self.height()))
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
PS C:\Users\IslamShahin\Documents\Custom Widget Example>  c:; cd 'c:\Users\IslamShahin\Documents\Custom Widget Example'; & 'C:\Users\IslamShahin\AppData\Local\Programs\Python\Python310\python.exe' 'c:\Users\IslamShahin\.vscode\extensions\ms-python.python-2023.2.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '55179' '--' 'c:\Users\IslamShahin\Documents\Custom Widget Example\main.py'

**Comment by islamshahine** [comment]
I'm using windows 10, python ver. 3.10

**Comment by islamshahine** [comment]
the problem lays here maybe:
File "C:\Users\IslamShahin\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Widgets.py", line 1152, in floatMenu
    self.setGeometry(QRect((self.parent().width() - self.width()) / 2, self.parent().height() - self.height(), self.width(), 
self.height()))

**Comment by islamshahine** [comment]
in widget.py file, I have updated the line to be:
`  if position == "bottom-center":
                    self.setGeometry(QRect(**int**((self.parent().width() - self.width()) / 2), self.parent().height() - self.height(), self.width(), self.height()))`

it worked!
