### ISSUE TITLE
Toggle Button issue with CustomSlideMenu

### ISSUE THREAD

**Issue by MrAmmia** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#52]
Following the instructions for animated side menu, I encounter the following

Traceback (most recent call last):
  File "C:\Users\Musa Abdullahi\Desktop\PyQt5GUI\main.py", line 66, in <module>
    window = MainWindow()
  File "C:\Users\Musa Abdullahi\Desktop\PyQt5GUI\main.py", line 39, in __init__
    loadJsonStyle(self, self.ui) 
  File "C:\Users\Musa Abdullahi\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Widgets.py", line 1492, in loadJsonStyle
    applyJsonStyle(self, self.ui, data)
  File "C:\Users\Musa Abdullahi\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Widgets.py", line 1604, in applyJsonStyle
    raise Exception("Error: Button named"+str(button)+" was not found.")
Exception: Error: Button namedpushButton was not found.

For some reason, it expects the toggle button to be in the QPushButtonGroups

**Comment by MrAmmia** [comment]
I've got it fixed, I had two Buttons array in my QPushButtonGroup in style.json, I deleted the one I didn't need and problem solved.
