### ISSUE TITLE
Not able to import Custom_Widgets.Widgets when PySide6 is used.

### ISSUE THREAD

**Issue by ovclara** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#53]
Hello,

I am trying out Custom_Widgets.Widgets library with PySide6.
But, getting issues with importing 

`
Type conversion already registered from type QFuture<QString> to type QFuture<void>
Traceback (most recent call last):
  File "d:\PySIDE6\Ui-Test\main.py", line 12, in <module>
    from Custom_Widgets.Widgets import *
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\Custom_Widgets\Widgets.py", line 12, in <module>
    import iconify as ico #pip install iconify
  File "C:\Users\<use>\AppData\Local\Programs\Python\Python310\lib\site-packages\iconify\__init__.py", line 1, in <module>   
    from . import anim, fetch, path  # noqa: F401
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\iconify\anim.py", line 8, in <module>       
    from iconify.qt import QtCore, QtGui
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\iconify\qt.py", line 28, in <module>        
    raise ImportError(_IMPORT_ERROR_MESSAGE.format(qtlib))
ImportError: Unable to import required Qt libraries from PySide2! Please set the 'ICONIFY_QTLIB' env var to the location of a Qt5 compliant python binding you would like to use.

`

Is there any pre-requisites required to work with PySide6?

Please guide to solve this issue.

**Comment by ovclara** [comment]
Still seems there are lot of issues- I have now moved to Pyside2 where it seems working fine.
But, when I try to create a exe out of it using pyinstaller or cx_freeze it do not work mainly due to "Module Custom_Widgets not found'
Can you please let me know how to solve this?

**Comment by KhamisiKibet** [comment]
newer version supports pyside6

**Comment by aileenfun** [comment]
> newer version supports pyside6

I'm using pyside6 and facing the same problem.

**Comment by bryancastillo10** [comment]
![image](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets/assets/64648492/877bbda3-bd88-4fea-8cec-39050a68d26c)
I am also encountering the same problem! Even though I already installed iconify, can you provide the requirements.txt so that we can check the dependency issues in using PySide6
