### ISSUE TITLE
'MainWindow' object has no attribute 'checkButtonGroup'

### ISSUE THREAD

**Issue by MK323F** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#82]
I was following along with your video,  and everything worked just fine. but yesterday i got this error i cannot solve on my own 

Traceback (most recent call last):
  File "D:\Python Projects\StonMillia\main.py", line 50, in <module>
    window = MainWindow()
  File "D:\Python Projects\StonMillia\main.py", line 28, in __init__
    loadJsonStyle(self, self.ui)
  File "C:\Users\MK323\AppData\Local\Programs\Python\Python39\lib\site-packages\Custom_Widgets\__init__.py", line 207, in loadJsonStyle
    applyJsonStyle(self, self.ui, data)
  File "C:\Users\MK323\AppData\Local\Programs\Python\Python39\lib\site-packages\Custom_Widgets\__init__.py", line 315, in applyJsonStyle
    btn.clicked.connect(self.checkButtonGroup)
AttributeError: 'MainWindow' object has no attribute 'checkButtonGroup'

I have tried defining the checkButtonGroup in the main file, and then the GUI does show up but my left menu is acting weird.
if i click on a button in the left menu it takes me to the page i clicked on, but the "Active" and "NotActive" from the style part does not work.

**Comment by MK323F** [comment]
NVM, found the problem. I imported some functions from pyside6 which were allready in the customwidgets.
Deleting the pyside6 import fixed the error
