### ISSUE TITLE
ModuleNotFoundError: No module named 'Custom_Widgets.__init__.QCustomQPushButton'

### ISSUE THREAD

**Issue by bha21** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#88]
After converting into .exe file below error shown:

Traceback (most recent call last):
  File "interface.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ui_interface.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "Custom_Widgets\Widgets.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "Custom_Widgets\QCustomProgressIndicator.py", line 20, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "Custom_Widgets\__init__.py", line 54, in <module>
ModuleNotFoundError: No module named 'Custom_Widgets.__init__.QCustomQPushButton'

Any solution of above error.

**Comment by MiguelRoncagliolo** [comment]
You need to go to you __init__.py on Custom_Wigets folder and change "from .QCustomQPushButton import applyAnimationThemeStyle, applyButtonShadow, iconify, applyCustomAnimationThemeStyle, applyStylesFromColor" to
"from Custom_Widgets.QCustomQPushButton import applyAnimationThemeStyle, applyButtonShadow, iconify, applyCustomAnimationThemeStyle, applyStylesFromColor"

This import it´s located in your 54 line
