### ISSUE TITLE
ModuleNotFoundError: No module named 'Custom_Widgets.__init__.Qss' 

### ISSUE THREAD

**Issue by MiguelRoncagliolo** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#91]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ui_interface.py", line 15, in <module>
    from Custom_Widgets.Widgets import QCustomSlideMenu
  File "C:\Users\MIGUEL~1\AppData\Local\Temp\embedded.iyk2ga5j.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "Custom_Widgets\Widgets.py", line 3, in <module>
  File "C:\Users\MIGUEL~1\AppData\Local\Temp\embedded.iyk2ga5j.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "Custom_Widgets\QCustomProgressIndicator.py", line 20, in <module>
  File "C:\Users\MIGUEL~1\AppData\Local\Temp\embedded.iyk2ga5j.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "Custom_Widgets\__init__.py", line 16, in <module>
  File "C:\Users\MIGUEL~1\AppData\Local\Temp\embedded.iyk2ga5j.zip\shibokensupport\__feature__.py", line 142, in _import
ModuleNotFoundError: No module named 'Custom_Widgets.__init__.Qss'
[21448] Failed to execute script 'main' due to unhandled exception!

I tried to convert my .py file to .exe, but I keep getting this error. Is ther any solution?

**Comment by MiguelRoncagliolo** [comment]
I tried this  changin this:

from Custom_Widgets.Qss import SassCompiler
CompileStyleSheet = SassCompiler.CompileStyleSheet
from Custom_Widgets.Qss.SvgToPngIcons import NewIconsGenerator
from Custom_Widgets.QCustomQPushButtonGroup import QCustomQPushButtonGroup

But I keep getting the same error
