### ISSUE TITLE
AttributeError: 'MainWindow' object has no attribute 'iconsWorker', AttributeError: 'PySide6.QtWidgets.QPushButton' object has no attribute 'setNewIcon'

### ISSUE THREAD

**Issue by samuelokpor** [KhamisiKibet/QT-PyQt-PySide-Custom-Widgets#93]
Hi i keep getting this error message when i try to run my app developed using Pyside6, how can i fix this error 

C:\Users\Dell\anaconda3b\envs\newenv\lib\site-packages\Custom_Widgets\Widgets.py:10: UserWarning: Deprecated imports. For 
more information, refer to the documentation at: https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3b\envs\newenv\lib\site-packages\Custom_Widgets\__init__.py", line 1045, in <lambda>
    getattr(self.ui, str(restore["buttonName"])).clicked.connect(lambda: self.restore_or_maximize_window())
  File "C:\Users\Dell\anaconda3b\envs\newenv\lib\site-packages\Custom_Widgets\__init__.py", line 107, in restore_or_maximize_window
    self.updateRestoreButtonIcon()
  File "C:\Users\Dell\anaconda3b\envs\newenv\lib\site-packages\Custom_Widgets\__init__.py", line 89, in updateRestoreButtonIcon
    self.restoreBtn.setNewIcon(str(self.maximizedIcon))
AttributeError: 'PySide6.QtWidgets.QPushButton' object has no attribute 'setNewIcon'
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3b\envs\newenv\lib\site-packages\Custom_Widgets\__init__.py", line 1045, in <lambda>
    getattr(self.ui, str(restore["buttonName"])).clicked.connect(lambda: self.restore_or_maximize_window())
  File "C:\Users\Dell\anaconda3b\envs\newenv\lib\site-packages\Custom_Widgets\__init__.py", line 107, in restore_or_maximize_window
    self.updateRestoreButtonIcon()
  File "C:\Users\Dell\anaconda3b\envs\newenv\lib\site-packages\Custom_Widgets\__init__.py", line 94, in updateRestoreButtonIcon
    self.restoreBtn.setNewIcon(str(self.normalIcon))
AttributeError: 'PySide6.QtWidgets.QPushButton' object has no attribute 'setNewIcon'
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3b\envs\newenv\lib\site-packages\Custom_Widgets\__init__.py", line 238, in stopWorkers      
    if self.iconsWorker is not None:
AttributeError: 'MainWindow' object has no attribute 'iconsWorker'

**Comment by KhamisiKibet** [comment]
Did you set your navigation buttons from JSon file?

**Comment by KhamisiKibet** [comment]
It seems like you did not use the Custom Widgets to generate compatible Ui interface files, run:

```cmd
Custom_Widgets --convert-ui ui-path --qt-library your-lib
```

For more, read [here](https://github.com/KhamisiKibet/QT-PyQt-PySide-Custom-Widgets?tab=readme-ov-file#version-069)

**Comment by bubble-xu** [comment]
I also encountered this problem. The problem appears in the following folder：python3.9/site-packages/Custom_Widgets/__init__.py, `    def stopWorkers(self):
        if self.iconsWorker is not None:
            self.iconsWorker.stop()

        if self.allIconsWorker is not None:
            self.allIconsWorker.stop()`

**Comment by KhamisiKibet** [comment]
Check that you have loaded your Json file correctly

**Comment by bubble-xu** [comment]
Thank you for your reply. In fact, I'm running the example in the pyside6 folder.QT-PyQt-PySide-Custom-Widgets-main/examples/PySide6/QMainWindow/main.py

**Comment by KhamisiKibet** [comment]
checking...

**Comment by bubble-xu** [comment]
OK, at present, main.py can run correctly, but when I exit the program, `QCoreApplication.instance().aboutToQuit.connect(self.stopWorkers)` will touch Send `Traceback (most recent call last):

File "/Users/bubble/opt/anaconda3/envs/zerenyungui/lib/python3.9/site-packages/Custom_Widgets/__init __.Py", line 241, in stopWorkers

If self.iconsWorker is not None:

AttributeError: 'MainWindow' object has no attribute 'iconsWorker'`
